name: Build & Push Docker image

on:
  push:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set repo owner lowercase
        id: repo
        run: echo "owner=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.repo.outputs.owner }}/vercel:latest .
          docker tag ghcr.io/${{ steps.repo.outputs.owner }}/vercel:latest ghcr.io/${{ steps.repo.outputs.owner }}/vercel:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ steps.repo.outputs.owner }}/vercel:latest
          docker push ghcr.io/${{ steps.repo.outputs.owner }}/vercel:${{ github.sha }}
